# Generated by Django 4.1.6 on 2023-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Job_Nature', models.CharField(choices=[('FULL TIME', 'FULL TIME'), ('PART TIME', 'PART TIME')], max_length=15)),
                ('Published_time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=1000)),
                ('Vacancy', models.IntegerField(default=1)),
                ('Salary', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
    ]
