# Generated by Django 4.1.6 on 2023-02-13 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Publisher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(upload_to=job.models.cv_upload),
        ),
    ]
